name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Build only on pushes to the main branch
  pull_request:
    branches:
      - main  # Optional: Build on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ping-pong-py"
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:v1.0.0 .

      # Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/ping-pong-py"
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:v1.0.0
