name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Build only on pushes to the main branch
  pull_request:
    branches:
      - main  # Optional: Build on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

